## Test 1.1 & 1.3 完成


In [1]:
import pandas as pd
import numpy as np
# A. Calculate the pairwise covariance matrix
def calculate_pairwise_covariance_matrix(data):
    return data.cov()


def calculate_missing_covariance(data):
    complete_data = data.dropna()
    cov_matrix = complete_data.cov()
    return cov_matrix

data = pd.read_csv('testfiles/data/test1.csv')
cov_matrix = calculate_pairwise_covariance_matrix(data)
print("Covariance Matrix (Pairwise Covariance Matrix):")
print(cov_matrix)
missing_matrix = calculate_missing_covariance(data)
print("Missing Covariance Matrix:")
print(missing_matrix)

Covariance Matrix (Pairwise Covariance Matrix):
          x1        x2        x3        x4        x5
x1  1.173986 -0.629631 -0.278932 -0.081448 -0.735140
x2 -0.629631  1.318197  0.018090  0.446047  0.139309
x3 -0.278932  0.018090  0.918102  0.360836  0.258613
x4 -0.081448  0.446047  0.360836  0.894764 -0.235190
x5 -0.735140  0.139309  0.258613 -0.235190  0.522607
Missing Covariance Matrix:
          x1        x2        x3        x4        x5
x1  2.148513 -1.389470 -0.516466 -0.129327 -1.056814
x2 -1.389470  1.035342  0.339993  0.193888  0.626876
x3 -0.516466  0.339993  0.942388  0.947887  0.051788
x4 -0.129327  0.193888  0.947887  1.113436 -0.204731
x5 -1.056814  0.626876  0.051788 -0.204731  0.592027


## Test 3.1 完成

In [14]:
# Check if the matrix is positive semi-definite
def is_positive_semi_definite(matrix):
    eigenvalues = np.linalg.eigvals(matrix)
    return np.all(eigenvalues >= 0), eigenvalues

def near_psd_rebonato_jackel(cov_matrix, epsilon=1e-8):
    # Step 1: Eigenvalue decomposition
    eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

    # Step 2: Replace negative eigenvalues with a small non-negative value
    eigenvalues[eigenvalues < 0] = epsilon

    # Step 3: Reconstruct the covariance matrix
    adjusted_cov_matrix = eigenvectors @ np.diag(eigenvalues) @ eigenvectors.T

    # Step 4: Rescale the matrix to match the original variances
    original_variances = np.diag(cov_matrix)
    scaling_factors = np.sqrt(original_variances / np.diag(adjusted_cov_matrix))
    scaling_matrix = np.diag(scaling_factors)
    final_cov_matrix = scaling_matrix @ adjusted_cov_matrix @ scaling_matrix

    return final_cov_matrix

data = pd.read_csv('testfiles/data/testout_1.3.csv')
psd_status, eigenvalues = is_positive_semi_definite(data)
print("Is the covariance matrix positive semi definite?", psd_status)
nearest_psd_matrix02 = near_psd_rebonato_jackel(data)
print("Nearest PSD Matrix (rebonato_jackel):")
print(nearest_psd_matrix02)

Is the covariance matrix positive semi definite? False
Nearest PSD Matrix (rebonato_jackel):
[[ 1.17398583 -0.62491041 -0.28191694 -0.07333608 -0.68749295]
 [-0.62491041  1.3181973   0.01757876  0.44569089  0.13695755]
 [-0.28191694  0.01757876  0.91810185  0.35676489  0.24242429]
 [-0.07333608  0.44569089  0.35676489  0.89476398 -0.21504184]
 [-0.68749295  0.13695755  0.24242429 -0.21504184  0.52260731]]


## Test 3.3 完成

In [32]:
import pandas as pd
import numpy as np
# B Check if the matrix is positive semi-definite
def is_positive_semi_definite(matrix):
    eigenvalues = np.linalg.eigvals(matrix)
    return np.all(eigenvalues >= 0), eigenvalues

def nearest_psd_higham(matrix, epsilon=1e-8):
    # Compute the symmetric part of the matrix
    sym_matrix = (matrix + matrix.T) / 2
    # Perform eigen-decomposition
    eigenvalues, eigenvectors = np.linalg.eigh(sym_matrix)
    # Replace negative eigenvalues with zero
    eigenvalues[eigenvalues < epsilon] = epsilon
    # print(eigenvalues)
    # Reconstruct the matrix
    return eigenvectors @ np.diag(eigenvalues) @ eigenvectors.T

data = pd.read_csv('testfiles/data/testout_1.3.csv')
psd_status, _ = is_positive_semi_definite(data)
print("Is the covariance matrix positive semi definite?", psd_status)


nearest_psd_matrix = nearest_psd_higham(data)
print("Nearest PSD Matrix (Higham):")
print(nearest_psd_matrix)

Is the covariance matrix positive semi definite? False


LinAlgError: Eigenvalues did not converge

In [10]:
import pandas as pd
import numpy as np
# B Check if the matrix is positive semi-definite
def is_positive_semi_definite(matrix):
    eigenvalues = np.linalg.eigvals(matrix)
    return np.all(eigenvalues >= 0), eigenvalues

def nearest_psd_higham_regularized(matrix, epsilon=1e-8, regularization=1e-6):
    # Compute the symmetric part of the matrix
    sym_matrix = (matrix + matrix.T) / 2
    print(sym_matrix)
    # Add regularization to diagonal
    sym_matrix += np.eye(sym_matrix.shape[0]) * regularization
    # Perform eigen-decomposition
    eigenvalues, eigenvectors = np.linalg.eigh(sym_matrix)
    # Replace negative eigenvalues with zero
    eigenvalues[eigenvalues < epsilon] = epsilon
    # Reconstruct the matrix
    return eigenvectors @ np.diag(eigenvalues) @ eigenvectors.T


data = pd.read_csv('testfiles/data/testout_1.3.csv')
psd_status, _ = is_positive_semi_definite(data)
print("Is the covariance matrix positive semi definite?", psd_status)

nearest_psd_matrix = nearest_psd_higham(data)
print("Nearest PSD Matrix (Higham):")
print(nearest_psd_matrix)

Is the covariance matrix positive semi definite? False


LinAlgError: Eigenvalues did not converge

In [ ]:
import numpy as np
import pandas as pd
from scipy.linalg import eigh

# A. Calculate the pairwise covariance matrix
def calculate_covariance_matrix(data):
    return data.cov()

# B. Check if the matrix is positive semi-definite
def is_positive_semi_definite(matrix):
    eigenvalues = np.linalg.eigvals(matrix)
    return np.all(eigenvalues >= 0), eigenvalues

# C. Find the nearest positive semi-definite matrix using Higham’s method
def nearest_psd_higham(matrix):
    # Compute the symmetric part of the matrix
    sym_matrix = (matrix + matrix.T) / 2
    # Perform eigen-decomposition
    eigenvalues, eigenvectors = np.linalg.eigh(sym_matrix)
    # Replace negative eigenvalues with zero
    eigenvalues[eigenvalues < 0] = 0
    # Reconstruct the matrix
    return eigenvectors @ np.diag(eigenvalues) @ eigenvectors.T

# D. Calculate covariance matrix using only overlapping data
def covariance_overlapping(data):
    overlapping_data = data.dropna()  # Drop rows with missing values
    return overlapping_data.cov()

# Main script
# Load the data (assuming the file is named 'problem2.csv')
data = pd.read_csv("problem2.csv")
# 1. Calculate covariance matrix
cov_matrix = calculate_covariance_matrix(data)
# 2. Check if the matrix is positive semi-definite
psd_status, eigenvalues = is_positive_semi_definite(cov_matrix)
print("Is the covariance matrix PSD?", psd_status)
# 3. Find the nearest PSD matrix using Higham's method
nearest_psd_matrix = nearest_psd_higham(cov_matrix)

# 4. Calculate covariance matrix using overlapping data
cov_matrix_overlapping = covariance_overlapping(data)

# 5. Compare the results
print("Original Covariance Matrix:")
print(cov_matrix)

print("Nearest PSD Matrix (Higham):")
print(nearest_psd_matrix)

print("Covariance Matrix Using Overlapping Data:")
print(cov_matrix_overlapping)

In [ ]:
def exponential_weights(n, lambda_):
    """
    Generate exponential weights for a time series of length n.

    Parameters:
        n (int): Length of the time series.
        lambda_ (float): Decay factor (0 < lambda_ < 1).

    Returns:
        weights (np.array): Array of exponential weights.
    """
    weights = (1 - lambda_) * (lambda_ ** np.arange(n - 1, -1, -1))
    weights /= weights.sum()  # Normalize weights to sum to 1
    return weights


def exponential_weighted_covariance(data, lambda_):
    """
    Calculate the exponentially weighted covariance matrix.

    Parameters:
        data (np.array or pd.DataFrame): Time series data (rows = observations, columns = variables).
        lambda_ (float): Decay factor (0 < lambda_ < 1).

    Returns:
        cov_matrix (np.array): Exponentially weighted covariance matrix.
    """
    if isinstance(data, pd.DataFrame):
        data = data.values

    n, m = data.shape
    weights = exponential_weights(n, lambda_)

    # Center the data (subtract the mean)
    centered_data = data - np.mean(data, axis=0)

    # Calculate the weighted covariance matrix
    cov_matrix = np.zeros((m, m))
    for i in range(m):
        for j in range(m):
            cov_matrix[i, j] = np.sum(weights * centered_data[:, i] * centered_data[:, j])

    return cov_matrix


# Example data (rows = time, columns = variables)
test_data = pd.read_csv("testfiles/data/test2.csv")
lambda_val = 0.97

# Calculate the exponentially weighted covariance matrix
ew_cov = exponential_weighted_covariance(test_data, lambda_val)
print("Exponentially Weighted Covariance Matrix:")
print(ew_cov)